### ISSUE TITLE
ziliqa API enebled corrupted start after DDOS

### ISSUE THREAD

**Issue by reb0rn21** [DurianStallSingapore/Zilliqa-Mining-Proxy#17]
After DDOS if I eneble zilliqa API i get all 0 at current block, next pow and log show:
if I disable API it works without it
also tried deleting whole zil_pow_windows from DB, did not help

[2019-03-09 16:06:42,217 ERROR  base_events.py:1608] Task exception was never retrieved
future: <Task finished coro=<Zilliqa.get_current_dsblock() done, defined at /home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py:283> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 68, in send_message
    self.endpoint, data=request, ssl=self.ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 285, in get_current_dsblock
    block = await cls.get_cache("dsblock", cls.api.GetCurrentDSEpoch)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 249, in get_cache
    val = await func(*args, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 42, in __call__
    resp = await self.api.call(self.method_name, *params, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 65, in call
    trim_log_values=True, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 99, in request
    validate_against_schema=validate_against_schema,
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 53, in send
    request_text, response_expected=response_expected, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 71, in send_message
    return Response(response_text, raw=response)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
[2019-03-09 16:06:42,217 ERROR  base_events.py:1608] Task exception was never retrieved
future: <Task finished coro=<Zilliqa.get_difficulty() done, defined at /home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py:291> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 68, in send_message
    self.endpoint, data=request, ssl=self.ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 294, in get_difficulty
    cls.api.GetPrevDifficulty)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 249, in get_cache
    val = await func(*args, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 42, in __call__
    resp = await self.api.call(self.method_name, *params, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 65, in call
    trim_log_values=True, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 99, in request
    validate_against_schema=validate_against_schema,
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 53, in send
    request_text, response_expected=response_expected, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 71, in send_message
    return Response(response_text, raw=response)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
[2019-03-09 16:06:42,218 ERROR  base_events.py:1608] Task exception was never retrieved
future: <Task finished coro=<Zilliqa.get_current_txblock() done, defined at /home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py:271> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 68, in send_message
    self.endpoint, data=request, ssl=self.ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 273, in get_current_txblock
    block = await cls.get_cache("txblock", cls.api.GetCurrentMiniEpoch)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 249, in get_cache
    val = await func(*args, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 42, in __call__
    resp = await self.api.call(self.method_name, *params, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 65, in call
    trim_log_values=True, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 99, in request
    validate_against_schema=validate_against_schema,
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 53, in send
    request_text, response_expected=response_expected, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 71, in send_message
    return Response(response_text, raw=response)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
[2019-03-09 16:06:42,218 ERROR  base_events.py:1608] Task exception was never retrieved
future: <Task finished coro=<Zilliqa.get_ds_difficulty() done, defined at /home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py:300> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 68, in send_message
    self.endpoint, data=request, ssl=self.ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 303, in get_ds_difficulty
    cls.api.GetPrevDSDifficulty)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/common/utils.py", line 249, in get_cache
    val = await func(*args, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 42, in __call__
    resp = await self.api.call(self.method_name, *params, **kwargs)
  File "/home/ubuntu/Zilliqa-Mining-Proxy/zilpool/pyzil/zilliqa_api.py", line 65, in call
    trim_log_values=True, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 99, in request
    validate_against_schema=validate_against_schema,
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/async_client.py", line 53, in send
    request_text, response_expected=response_expected, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jsonrpcclient-3.3.1-py3.7.egg/jsonrpcclient/clients/aiohttp_client.py", line 71, in send_message
    return Response(response_text, raw=response)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

**Comment by cryptowhizzard** [comment]
Are you sure your internet provider does not filter out the nessecary trafic to make it work?

**Comment by reb0rn21** [comment]
I am sure that it does not

**Comment by Swaggadan** [comment]
what was done to solve problem?

**Comment by Swaggadan** [comment]
> Yeah was due host, on new it works

What was done to solve problem? I see below message on my private proxy.
"ERROR  base_events.py:1608] Task exception was never retrieved"
