### ISSUE TITLE
Api2 Nicehash error

### ISSUE THREAD

**Issue by cryptowhizzard** [DurianStallSingapore/Zilliqa-Mining-Proxy#27]
Error when accessing top_price()

[2019-11-09 21:07:10,840 ERROR base_events.py:1608] Task exception was never retrieved
future: <Task finished coro=<nice_hash_task() done, defined at /root/Zilliqa-Mining-Proxy/zilpool/poolserver.py:229> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
File "/root/Zilliqa-Mining-Proxy/zilpool/poolserver.py", line 253, in nice_hash_task
privApi.keep_my_orders_top()
File "/root/Zilliqa-Mining-Proxy/zilpool/nicehash.py", line 317, in keep_my_orders_top
max_price=max_price)
File "/root/Zilliqa-Mining-Proxy/zilpool/nicehash.py", line 275, in get_top_price
full_orders = pubAPI.get_active_orders2()
File "/root/Zilliqa-Mining-Proxy/zilpool/nicehash.py", line 55, in get_active_orders2
daggerOrders = [order for order in response if order['algorithm'] == 'DAGGERHASHIMOTO' and order['market'] == 'USA']
File "/root/Zilliqa-Mining-Proxy/zilpool/nicehash.py", line 55, in 
daggerOrders = [order for order in response if order['algorithm'] == 'DAGGERHASHIMOTO' and order['market'] == 'USA']
TypeError: string indices must be integers

**Comment by ShengguangXiao** [comment]
It has been fixed in the latest commit, please pull again and try.
